### ISSUE TITLE
Compatibility YARP 3.0

### ISSUE THREAD

**Issue by jeljaik** [robotology/yarp-joypad-tools#3]
Hello guys, 

I'm now using YARP 3.0.100 with all my projects but since `yarp-joypad-tools` **requires**  2.3.69.9 I'm getting compilation errors. I see it does not really require 3.0, but can we make this just a minimum requirement?

**Comment by traversaro** [comment]
Fixed by https://github.com/robotology/yarp-joypad-tools/commit/2b23773238ffcda3f381d72a12895a570ef3f9d4 .

**Comment by jeljaik** [comment]
Jenkins thanks you!
